server:
  port: 8080
spring:
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.113.151.37:3306/reggie?serverTimezone=UTC&userUnicode=true&useSSL=false&
      username: root
      password: root
  mvc:
    dispatch-options-request: true
    view:
      suffix: /
      prefix: .html
  web:
    resources:
      static-locations: "classpath:/backend/**"
  redis:
    port: 6379
    host: 47.113.151.37
    database: 0
  cache:
    redis:
      time-to-live: 1800000 #设置redis缓存存活时间，单位毫秒

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

reggie:
  path: ReggieApp\img\
#  path: D:\img\